// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH38b0CfI4wf5-7zZLFThDRStzReu_nxY',
    appId: '1:259757111315:android:67edc07de759a1d583e7e6',
    messagingSenderId: '259757111315',
    projectId: 'mynotes-phoenix-developm-17faf',
    storageBucket: 'mynotes-phoenix-developm-17faf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_bB7-9KpEGPESh0kqeHbFN8A9rila6M',
    appId: '1:259757111315:ios:5a08fa50e8844c7383e7e6',
    messagingSenderId: '259757111315',
    projectId: 'mynotes-phoenix-developm-17faf',
    storageBucket: 'mynotes-phoenix-developm-17faf.appspot.com',
    iosClientId:
        '259757111315-hbgpa0s6gnnrc32pq81df0rdt89svsdi.apps.googleusercontent.com',
    iosBundleId: 'com.phoenix.mynotes',
  );
}
